### ISSUE TITLE
the four reward metrics

### ISSUE THREAD

**Issue by THBUer-yw** [uclaml/SPIN#16]
I wonder how the four reward metrics **rewards/real**, **rewards/generated**, **rewards/accuracies** and **rewards/margins** change during training? Can you show some pictures about them for reimplement？

**Comment by angelahzyuan** [comment]
![00685576-926e-473d-ae4a-26454b7c7ba6](https://github.com/uclaml/SPIN/assets/120995000/323a5952-a84f-4417-979f-eddf7668c531)

An example from iter3. Behavior may vary in different settings. The connection of these metrics to the final evaluation is not obvious.
