### ISSUE TITLE
vllm generation issue.

### ISSUE THREAD

**Issue by tdolan21** [uclaml/SPIN#3]
i believe that the argument used in generate_vllm.sh is supposed to be `batch_size` rather than `world_size`. When I make that change the script starts working immediately.

**Comment by yihedeng9** [comment]
Hello. The arguments for generate_vllm.py and generate_vllm.sh were both `world_size`. We have unified this to `batch_size` as in generate.py in our latest commit. Thanks for bringing it up!

**Comment by yihedeng9** [comment]
Also, the previous `generate_vllm.sh` seems to be wrongly calling `generate.py`. You may want to make sure to be using `generate_vllm.py` (refer to the latest updates script).
