### ISSUE TITLE
vllm version

### ISSUE THREAD

**Issue by zhaochenyang20** [uclaml/SPIN#6]
Hey @uclaml and @yihedeng9,

I noticed that your setup tools depend on `vllm`. Given that vllm is still under rapid development, and considering your implementation incorporates the `tensor_parallel_size` parameter, it might be prudent to specify a particular version of `vllm`. Additionally, including `ray` in your setup tools could be beneficial, as `vllm`'s multi-GPU inference relies on it. 🤔

Thanks for your attention!

**Comment by zhaochenyang20** [comment]
Yeah. I also see a closed issue regarding `vllm`. It's a rapidly developing framework. It may be better to use it with caution. 😂

**Comment by yihedeng9** [comment]
Hi, thank you for bringing the issue up! We will make an update on the setup file soon.
